package com.example.flight.domain.model.flight

data class FlightData(
    val flight0: Flight? = null,
    val flight1: Flight? = null,
    val flight2: Flight? = null,
    val flight3: Flight? = null,
    val flight4: Flight? = null,
    val flight5: Flight? = null,
    val flight6: Flight? = null,
    val flight7: Flight? = null,
    val flight8: Flight? = null,
    val flight9: Flight? = null,
    val flight10: Flight? = null,
    val flight11: Flight? = null,
    val flight12: Flight? = null,
    val flight13: Flight? = null,
    val flight14: Flight? = null,
    val flight15: Flight? = null,
    val flight16: Flight? = null,
    val flight17: Flight? = null,
    val flight18: Flight? = null,
    val flight19: Flight? = null,
    val flight20: Flight? = null,
    val flight21: Flight? = null,
    val flight22: Flight? = null,
    val flight23: Flight? = null,
    val flight24: Flight? = null,
    val flight25: Flight? = null,
    val flight26: Flight? = null,
    val flight27: Flight? = null,
    val flight28: Flight? = null,
    val flight29: Flight? = null,

)
